import { getTheme } from './themes'
import type { CustomThemeColors, Project } from '../types'

/**
 * Re-colours a project generated by our templates when the student switches
 * theme after creation (including to/from a custom colour scheme). Works by
 * remapping the *old* theme's exact palette values to the *new* theme's —
 * since every generated slide/shape only ever uses `primary` /
 * `primaryDark` / `accent` / `surfaceTint` / `onPrimary`, this swap is
 * deterministic and leaves any colour the student picked by hand (anything
 * outside the old palette) untouched.
 */
export function applyThemeToProject(project: Project, newThemeId: string, newCustom?: CustomThemeColors): Project {
  const oldTheme = getTheme(project.theme, project.customTheme)
  const newTheme = getTheme(newThemeId, newCustom)
  if (oldTheme.id === newTheme.id && oldTheme.primary === newTheme.primary && oldTheme.accent === newTheme.accent) {
    return { ...project, theme: newThemeId, customTheme: newCustom }
  }

  const map = new Map<string, string>([
    [oldTheme.primary.toLowerCase(), newTheme.primary],
    [oldTheme.primaryDark.toLowerCase(), newTheme.primaryDark],
    [oldTheme.accent.toLowerCase(), newTheme.accent],
    [oldTheme.surfaceTint.toLowerCase(), newTheme.surfaceTint],
    [oldTheme.onPrimary.toLowerCase(), newTheme.onPrimary],
  ])
  const recolor = (hex: string) => map.get(hex.toLowerCase()) ?? hex

  return {
    ...project,
    theme: newThemeId,
    customTheme: newCustom,
    slides: project.slides.map((slide) => ({
      ...slide,
      background: recolor(slide.background),
      blocks: slide.blocks.map((block) => {
        if (block.type === 'shape') return { ...block, color: recolor(block.color) }
        if (block.type === 'text') return { ...block, color: recolor(block.color) }
        return block
      }),
    })),
  }
}
